Update main_K8S.yml

diff --git a/.github/workflows/main_K8S.yml b/.github/workflows/main_K8S.yml
--- a/.github/workflows/main_K8S.yml
+++ b/.github/workflows/main_K8S.yml
@@ -29,9 +29,17 @@ jobs:
         run: |
           mkdir -p /opt/tmp  # Ensure the directory exists
           secret_response="${{ steps.secretsafe.outputs.docker }}"
+    
+          # Check if secret_response is empty or invalid
+          if [ -z "$secret_response" ]; then
+            echo "Error: Secret response is empty!"
+            exit 1
+          fi
+    
+          echo "$secret_response" | jq empty || { echo "Invalid JSON format!"; exit 1; }
+    
           secret=$(echo "$secret_response" | jq -r '.value')
           echo "$secret" > /opt/tmp/secret.txt
-
       - name: Debug Secret Content
         run: |
           echo "Secret content:"
